# rename this file to evcenter.yml and put a ':' after 'name' if
# you want to use YAML like in old versions of Catalyst
name EVCenter

<Plugin::SmartURI>
    disposition relative   # application-wide
    uri_class   URI::SmartURI # by default
</Plugin::SmartURI>

<Model::Processor>
    <args>
        includes lib/EVCenter/Includes
    </args>
</Model::Processor>

# ENVIRONMENT VARIABLES WILL OVERRIDE THESE SETTINGS
# You can set these environment variables to override the settings in this file:
# EVCENTER_DBHOST, EVCENTER_DBNAME, EVCENTER_DBUSER, EVCENTER_DBPASS, EVCENTER_DBPORT, EVCENTER_DBOPTS

<Model::AuthDB>
    schema_class Auth::Schema
    <connect_info>
        dsn dbi:Pg:dbname=__ENV(EVCENTER_DBNAME)__;host=__ENV(EVCENTER_DBHOST)__;port=__ENV(EVCENTER_DBPORT)__
        user __ENV(EVCENTER_DBUSER)__
        password __ENV(EVCENTER_DBPASS)__
        AutoCommit 1
        pg_enable_utf8 1
    </connect_info>
</Model::AuthDB>

<Model::Event>
    <args>
        dbhost __ENV(EVCENTER_DBHOST)__
        dbname __ENV(EVCENTER_DBNAME)__
        dbuser __ENV(EVCENTER_DBUSER)__
        dbpass __ENV(EVCENTER_DBPASS)__
        dbport __ENV(EVCENTER_DBPORT)__
        dbopts ""
        <dbi_opts>
            AutoCommit 1
        </dbi_opts>
    </args>
</Model::Event>

<Model::ACL>
    <args>
        dbhost __ENV(EVCENTER_DBHOST)__
        dbname __ENV(EVCENTER_DBNAME)__
        dbuser __ENV(EVCENTER_DBUSER)__
        dbpass __ENV(EVCENTER_DBPASS)__
        dbport __ENV(EVCENTER_DBPORT)__
        dbopts ""
        <dbi_opts>
            AutoCommit 1
        </dbi_opts>
    </args>
</Model::ACL>

<Model::UserControl>
    <args>
        dbhost __ENV(EVCENTER_DBHOST)__
        dbname __ENV(EVCENTER_DBNAME)__
        dbuser __ENV(EVCENTER_DBUSER)__
        dbpass __ENV(EVCENTER_DBPASS)__
        dbport __ENV(EVCENTER_DBPORT)__
        dbopts ""
        <dbi_opts>
            AutoCommit 1
        </dbi_opts>
    </args>
</Model::UserControl>