---
abstract: 'Catalyst based application'
author:
  - 'João André Simioni'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EVCenter
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Model::Adaptor: 0
  Catalyst::Plugin::Compress: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Server::JSONRPC: 0
  Catalyst::Plugin::Session::State::Stash: 0
  Catalyst::Plugin::Session::Store::File: 0
  Catalyst::Plugin::SmartURI: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode: 0
  Catalyst::Runtime: 5.90042
  Catalyst::View::JSON: 0
  Catalyst::View::TT: 0
  Config::General: 0
  DBD::Pg: 0
  DBIx::Connector: 0
  Hash::Merge::Simple: 0
  JSON::MaybeXS: 0
  Log::Any::Adapter::Catalyst: 0
  Module::Pluggable::Object: 0
  Moose: 0
  Net::SNMP: 0
  SQL::Abstract::More: 0
  common::sense: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
