#!/bin/bash

PGPASSWORD=$EVCENTER_DBPASS psql -U $EVCENTER_DBUSER -d $EVCENTER_DBNAME -h $EVCENTER_DBHOST -p $EVCENTER_DBPORT -c "SELECT delete_cleared();"
PGPASSWORD=$EVCENTER_DBPASS psql -U $EVCENTER_DBUSER -d $EVCENTER_DBNAME -h $EVCENTER_DBHOST -p $EVCENTER_DBPORT -c "SELECT delete_expired();"