#!/bin/bash

export PERL5LIB="${PERL5LIB:-.:lib}"
export EVCENTER_DBHOST="${EVCENTER_DBHOST:-localhost}"
export EVCENTER_DBNAME="${EVCENTER_DBNAME:-evcenter}"
export EVCENTER_DBUSER="${EVCENTER_DBUSER:-evcenter}"
export EVCENTER_DBPASS="${EVCENTER_DBPASS:-evcenter}"
export EVCENTER_DBPORT="${EVCENTER_DBPORT:-5432}"
export EVCENTER_MODE="${EVCENTER_MODE:-development}"

PGPASSWORD=$EVCENTER_DBPASS psql -U $EVCENTER_DBUSER -d $EVCENTER_DBNAME -h $EVCENTER_DBHOST -p $EVCENTER_DBPORT -c "SELECT delete_cleared();"
PGPASSWORD=$EVCENTER_DBPASS psql -U $EVCENTER_DBUSER -d $EVCENTER_DBNAME -h $EVCENTER_DBHOST -p $EVCENTER_DBPORT -c "SELECT delete_expired();"