package EVCenter::Model::AuthDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Auth::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=evcenter',
        #user => '',
        #password => '',
    }
);

=head1 NAME

EVCenter::Model::AuthDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<EVCenter>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Auth::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.4

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
