#!/usr/bin/perl

use DBI;
use Time::HiRes qw( tv_interval gettimeofday );

my $dbh = DBI->connect("dbi:Pg:dbname=evcenter", '', '', { AutoCommit => 0 });

my @hosts;
my @types = (1, 2);
my @groups = ('Link', 'CPU', 'Memory', 'Chassis', 'Caneta', 'Borracha', 'TV');
my @objects = ('Board', 'Interface', 'Shelf', 'Grilo', 'Elefante', 'Jaspion');

for (1..290) {
    push @hosts, "HOST$_";
}

my $count = 0;
my $sth;
my $last = [gettimeofday];
while (1) {
    if ($count % 10 == 0) {
            $dbh->commit;
            $sth = $dbh->prepare("INSERT INTO active_events (dedup_id, event_id, node, object, type, event_group, severity, message)
                                         VALUES (?, ?, ?, ?, ?, ?, ?, ?)");
    }

    my $host   = $hosts[rand @hosts];
    my $type   = $types[rand @types];
    my $group  = $groups[rand @groups];
    my $object = $objects[rand @objects];

    my $severity = $type == 1 ? 5 : 1;

    my $message  = 'Fake Event Generated by the system';

    my $dedup_id = join(' ', $host, $type, $group, $object);
    my $event_id = join(' ', $host, $group, $object);

    $sth->execute($dedup_id, $event_id, $host, $object, $type, $group, $severity, $message);

    # print "Count: ", $count++, "\n";
    $count++;

    if ($count % 500 == 0) {
	$elapsed = tv_interval ( $last, [gettimeofday]);
        print "Eventos / segundo = ", 500 / $elapsed, "\n";    
        $last = [gettimeofday];
    }
}
